# Generated by Django 5.1.7 on 2025-03-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0003_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='last_successful_push',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
